### PR TITLE
Move away from Highcharts

### PR DESCRIPTION
**Pull request by brunocodutra**
This pull request addresses #9

### CODE REVIEW

**Comment by brunocodutra** [comment]
metabench.cmake is now REALLY cluttered by thousands of lines of escaped javascript code, but I think the benefit of being totally offline is worth it.

**Comment by ldionne** [comment]
Looks cool. I assume you used a script to escape the javascript? Perhaps it would be a good idea to add the script to the repository if we ever want to update the dependencies.

**Comment by ldionne** [comment]
Also, do you know how we could provide a title (and subtitle) to the chart? I searched on Google, but it seems like we can't do it from the JSON and we'd have to do it in JavaScript.

**Comment by brunocodutra** [comment]
Nothing fancy, just very simple and hacky perl scripts to insert a line break every 80 characters, then escape backslashes and double quotes. I'll add it as a self-contained script to `tools/` later today.

NVD3 doesn't seem have a builtin way to add titles to `lineChart`s, but we could always do it manually using javascript. Indeed, if you look closer you will realize that I actually manually extract information from the JSON in order to setup the chart, as there's no `renderto` equivalent in NVD3. I'll add something to dynamically create labels based on two new properties `title` and `subtitle`. Would it be enough to just expect the string to be displayed?

**Comment by ldionne** [comment]
> Would it be enough to just expect the string to be displayed?

Yes, it would be enough.

**Comment by brunocodutra** [comment]
This should be ready for merging now.

**Comment by ldionne** [comment]
Awesome, thanks a lot!

**Pull request merged**
