### PR TITLE
Add support for Appveyor

### LINKED ISSUE #4: Metabench should  be tested on windows
I think it wouldn't be too hard to set up Appveyor.

### PR DESCRIPTION
**Pull request by ldionne**
This pull request adds support for testing Metabench on Windows. Once merged, this will fix #4.

### CODE REVIEW

**Comment by brunocodutra** [comment]
just a heads up, instead of setting `-std=c++11`, which is not understood by MSVC, we can raise CMake minimum version to 3.1 and use the following instead

`set(CMAKE_CXX_STANDARD 11)`
`set(CMAKE_CXX_STANDARD_REQUIRED ON)`

This way we could test MSVC on windows, since we are delegating the compilation to CMake already anyways.

**Comment by ldionne** [comment]
Yup, thanks, I'm already doing this :) But I didn't know it was CMake >= 3.1, so I'll update that. I'm almost there for Appveyor support.

**Comment by brunocodutra** [comment]
crap, just realized it :I

but yeah, I think it is >= 3.1.

**Comment by brunocodutra** [comment]
So is there anything still preventing us from testing MSVC?

**Comment by ldionne** [comment]
Technically, no, although I wanted to first get it working with Clang-cl because I already had the Appveyor script from Hana and I've no idea how to use MSVC.

**Comment by brunocodutra** [comment]
[I use it to test Metal](https://github.com/brunocodutra/metal/blob/master/appveyor.yml), but I don't think I'm using a "Makefile Generator" there.

**Comment by ldionne** [comment]
No, you're not using a Makefile Generator. It's certainly possible to pass MSVC as `CMAKE_CXX_COMPILER`, though?

**Comment by brunocodutra** [comment]
I'd guess we could use "NMake Makefiles" and "NMake Makefiles JOM", while setting CMAKE_CXX_COMPILER to `<path to msvc binaries>/cl.exe`

**Comment by brunocodutra** [comment]
Perhaps when calling `vcvarsall.bat` the appropriate `cl.exe` is added to PATH, so we wouldn't need the absolute path.

**Comment by ldionne** [comment]
Now that basic Appveyor support is locked down (finally...), let's move to #18.

**Pull request merged**
