### PR TITLE
Make sure we generate charts

### LINKED ISSUE #23: We currently do not output any HTML or JSON chart
The double-quoting added in 356855af57fa1640df4c8f4a020e8accc13dd972 had the effect of turning all the commands we were executing into Ruby strings. So we were evaluating the strings containing our code instead of the code itself.

### PR DESCRIPTION
**Pull request by ldionne**
This PR is an attempt to fix #23. I'm submitting as a PR instead of merging into master, because I think that might break some generators so I might still need to adjust some things.

### CODE REVIEW

**Comment by brunocodutra** [comment]
As part of #21 I made some changes to `run_tests.sh` in order to check whether `check.json` and `check.html` are generated.

I'm cherry picking this into a new PR.

**Comment by ldionne** [comment]
> I'm cherry picking this into a new PR.

No need, i'll merge these change. I'd rather not tie the `run_test.sh` too much to the actual tests, which is why I added the check through CMake.

**Comment by brunocodutra** [comment]
> [...] which is why I added the check through CMake.

Much better.

**Comment by ldionne** [comment]
@brunocodutra I realize that merging this might give you some conflicts when you'll rebase #21. However, recovering basic functionality is, I think, the number 1 priority for now.

**Comment by brunocodutra** [comment]
> I realize that merging this might give you some conflicts when you'll rebase #21. However, recovering basic functionality is, I think, the number 1 priority for now.

Of course, no problem.

**Pull request merged**
