### PR TITLE
add_benchmark should be immune to absolute paths

### PR DESCRIPTION
**Pull request by brunocodutra**
this way one may safely 

`add_benchmark(path.to.benchmark "${CMAKE_CURRENT_SOURCE_DIR}/path/to/benchmark")`

### CODE REVIEW

**Comment by brunocodutra** [comment]
Because otherwise if an absolute path is used you'd have `_metabench/a/hell/of/a/long/prefix/path/to/benchmark` instead of the expected `_metabench/path/to/benchmark`.

**Comment by ldionne** [comment]
Well no, because you would just have made the path relative with `string(REPLACE ...)`?

**Comment by ldionne** [comment]
In other words, we're making the `path_to_dir` relative to the current source directory using the `string(REPLACE ...)`. From then on, it should be safe to assume that the path is relative to the current source dir, and so we can use the relative path in the `file(GLOB ...)` call.

**Comment by brunocodutra** [comment]
I don't get it, what you mean?
The idea is to strip `${CMAKE_CURRENT_SOURCE_DIR}` from `path_to_dir`, since the latter is used to create the output json file.
If we don't erase `${CMAKE_CURRENT_SOURCE_DIR}`, the we would get a very long prefix.

And I'm pretty sure CMake deals with such windows nastiness for us.

**Comment by brunocodutra** [comment]
To test, try this out `add_benchmark(path.to.benchmark "${CMAKE_CURRENT_SOURCE_DIR}/path/to/benchmark")`

**Comment by ldionne** [comment]
I understand the purpose of line 40 of your patch, but not lines 44 to 47. That is my question.

**Comment by brunocodutra** [comment]
Oh I see, I don't know, they are probably unnecessary, but I taught myself to be strict when it comes to pathnames because I've shot myself in the foot far too many times due to stupid relative paths.

I can revert those lines if you want.

**Comment by brunocodutra** [comment]
I mean, they don't hurt either right?

**Comment by ldionne** [comment]
Ok, I just wanted to see whether I was missing something. It's fine this way.

**Comment by brunocodutra** [comment]
Oh just realized you can actually comment pull requests line by line.
Sorry for the mess.

**Comment by ldionne** [comment]
> Oh just realized you can actually comment pull requests line by line.

Yes, it's handy! No problem!

**Pull request merged**
