### PR TITLE
Made metabench use the system + user time for his measurements instea…

### PR DESCRIPTION
**Pull request by CvRXX**
…d of just the raw time. This means that the time will be less influenced by other processes runnig on the system. Idea for this commit came from @chieltbest

### CODE REVIEW

**Comment by brunocodutra** [comment]
Sounds awsome, does it improve results noticeably?

**Comment by ldionne** [comment]
I just generated the benchmarks with this patch on my laptop, and the results actually appear to have more variability.

**Comment by ldionne** [comment]
Actually, it could be that real time is measured with more precision, which means that _total_ time ends up giving more steps in the charts. I do agree that, in theory, total time is most likely what we should be measuring, but in practice it does not seem to give the best results on my laptop. I'll launch the benchmarks on Travis and push them temporarily to some dummy branch so we can look at them.

**Comment by CvRXX** [comment]
Looking forward to the results!

**Comment by CvRXX** [comment]
user + system time is less accurate so you will get more variability in small tests but there will be less noise from other processes in bigger tests. Maybe make a switch for it?

**Comment by ldionne** [comment]
Actually, it appears to significantly improve the reliability of results. See this, where the left hand side is the benchmarks generated with this patch, and the right hand side is without the patch: 
metabench

**Comment by brunocodutra** [comment]
can we afford to disable `MEDIAN_OF` and solve #145 for now?

**Comment by ldionne** [comment]
> can we afford to disable MEDIAN_OF and solve #145 for now?

Checking: https://travis-ci.org/ldionne/metabench/builds/158330425

**Comment by brunocodutra** [comment]
Am I screwing something up or are results exactly the same on branch `gh-pages` and `gh-pages-nomedian`?

**Comment by ldionne** [comment]
IDK what went wrong; running again: https://travis-ci.org/ldionne/metabench/builds/158625013

**Comment by ldionne** [comment]
Ok; I just compared the results and it appears that we're not significantly worse without the median filter. In fact, the variability of our data is huge in all cases for small sequence sizes, which sucks. I think #148 would add a lot of value to the suite. Either way, I'll disable the median filter for the benchmark suite and resolve #145 for now.

**Pull request merged**
