### PR TITLE
added library Kvasir

### PR DESCRIPTION
**Pull request by odinthenerd**

### CODE REVIEW

**Comment by odinthenerd** [comment]
older clang failing, funny clang 3.7 with microsoft codegen works, guess I need to install clang 3.6. Is there a way to exclude tests on old clang for now ?

**Comment by ldionne** [comment]
Try looking at what we do for Hana on old GCCs

**Comment by odinthenerd** [comment]
looks like the porblem occurs with our wrappers around meta continuations. here is a short example of the problem https://godbolt.org/g/l2jkT8 I think we can solve this without too much trouble.

**Comment by brunocodutra** [comment]
Reposting from cpplang for future reference:

> working around the issue with the fixed type is easy, just make sure the nested alias template is dependent somehow, like this: https://godbolt.org/g/8dQoAc

**Comment by odinthenerd** [comment]
clang 3.5, 3.6, 3.7 will be slower because I force a lazy instantiation to get around the alias flaw but should work now

**Comment by ldionne** [comment]
If you're ready to merge, can you please squash into a sensible set of commits? Just edit your branch locally and then push-force. That will update the PR; no need to create a new PR.

**Comment by brunocodutra** [comment]
and update the copyright notices on top of each file

**Comment by odinthenerd** [comment]
OK ready to go, I'm always a bit timid when it comes to --force ;)

**Pull request merged**
