### PR TITLE
Allow specifying a title in add_benchmark

### PR DESCRIPTION
**Pull request by ldionne**
While this may not be useful for the benchmark suite because of the way http://ldionne.com/metabench is setup, I need this capability for some uses of Metabench in presentations.

### CODE REVIEW

**Comment by brunocodutra** [comment]
Just for the record, I'm totally in favour of providing additional features in order to make sure Metabench is useful beyond the benchmark suite.

That said, I think we should broaden the scope of this PR to tackle #60, so basically we have to:

1. Stop generating the aggregate JSON file and, from now on, regard `metabench_add_benchmark` as semantically equivalent to "add chart". 
2. Get rid of `chart.json` and, instead, add new parameters to `metabench_add_benchmark` which would be used for the configuration of the output HTML file (the first of which is `TITLE`).
3. Make the individual JSON files produced by each `dataset` public (and ultimately serve them through `gh-pages` as in #71)

What do you think?

**Comment by ldionne** [comment]
> What do you think?

I think that is the right thing to do.

**Comment by ldionne** [comment]
I think getting rid of `chart.json` and adding new parameters to `metabench_add_benchmark` is a nontrivial task. Let's say we want to allow setting the axis labels. Right now, we're also setting the tick precision because we know the Y axis represents the time. But what if this is not true anymore? I suggest we defer the task of adding more parameters to another PR, and keep `chart.json` for the time being.

**Comment by brunocodutra** [comment]
Actually I think the opposite, we should not give the user too much control over NVD3, because it can break very easily.

Tick precision for example should never be set by the user, since it's Metabench who's in control of what data is generated. IMO it should be set by `metabench_add_benchmark` in accordance to the parameter which controls whether we want a chart for time, binary size or whatever (`ASPECT` perhaps?).

Do you see any need for anything besides `TITLE`, `SUBTITLE`, `XLABEL`, `YLABEL` and `APSECT`? These seem reasonably easy to setup.

**Comment by ldionne** [comment]
I agree with you, and I think the customization points you suggest should suffice (at least for now). Also, if we have `ASPECT`, I don't think we need `YLABEL`, since these are somewhat equivalent.

**Comment by brunocodutra** [comment]
> Also, if we have ASPECT, I don't think we need YLABEL, since these are somewhat equivalent.

Good point, it can certainly be defaulted in accordance to `ASPECT`, however I think we should still provide it in case the user wants to provide labels in a different idiom for example.

**Comment by ldionne** [comment]
Ok; I'll handle your points (1) and (3) above in PR #103. This PR will handle point (2).

**Comment by ldionne** [comment]
This will also address #34.

**Comment by ldionne** [comment]
@brunocodutra By the way, the title is sometimes overlapping the legend, but I don't know how to workaround it:
screen shot 2016-04-08 at 12 20 57

**Comment by brunocodutra** [comment]
> By the way, the title is sometimes overlapping the legend, but I don't know how to workaround it

Well, we could lower the title about `1em`, would that work for you?

**Comment by ldionne** [comment]
I lowered the subtitle too, and it appears to work as a charm.

**Comment by ldionne** [comment]
If you're fine with this (i.e. I did not butcher the JS chart creation too much), I'll merge this.

**Comment by brunocodutra** [comment]
> If you're fine with this (i.e. I did not butcher the JS chart creation too much), I'll merge this.

Looks great

**Pull request merged**
