### PR TITLE
add a direct link for each chart

### PR DESCRIPTION
**Pull request by brunocodutra**

### CODE REVIEW

**Comment by brunocodutra** [comment]
Do you think you could manually merge this? I don't know why git complains, it should simply be a matter of adding these lines.

**Comment by ldionne** [comment]
I was able to rebase it onto `gh-pages`; it fails to merge automatically because the surrounding context changed. However, this adds the button to the bar itself, and thus clicking on the button causes the chart to expand, which I think is odd.

Try ctrl+click on the button; it will open the chart in a new tab __and__ expand the chart. I think it should only open the chart in a new tab.

**Comment by brunocodutra** [comment]
> However, this adds the button to the bar itself, and thus clicking on the button causes the chart to expand, which I think is odd.

On what browser are you testing? It didn't behave like this on chromium at least.

**Comment by ldionne** [comment]
Safari, but Chrome behaves the same. I must have changed something in the original PR when rebasing it.

**Comment by brunocodutra** [comment]
> Safari, but Chrome behaves the same. 

Weird, I'll investigate.
In any case stopping propagation should fix this issue, thanks for testing.

**Comment by brunocodutra** [comment]
Rebased atop `gh-pages`.

I still can't reproduce the issue on neither:

* Chromium 49.0.2623.110
* Mozilla Firefox 45.0.1

Could you test again please? Specially on Safari to which I don't have access.

**Comment by ldionne** [comment]
metabench-panel-expansion

First is Safari. You can see that each time I cmd+click the little icon, a new tab opens up with the chart, but it also expands the panel.

**Comment by brunocodutra** [comment]
I'll be damned.

**Comment by brunocodutra** [comment]
Oh, now I get it, ctrl + click is different from clicking the scroll button.

**Comment by ldionne** [comment]
IDK, my trackpad has no scroll button :p

**Comment by brunocodutra** [comment]
should be fixed now

**Pull request merged**
