### PR TITLE
update metal to v0.4.0

### PR DESCRIPTION
**Pull request by brunocodutra**
Update Metal benchmarks to the latest version (see brunocodutra/metal#53)

### CODE REVIEW

**Comment by brunocodutra** [comment]
it seems all builds have been failing with 

> The command "wget --no-check-certificate --quiet -O - https://sourceforge.net/projects/boost/files/latest/download" failed. 

any idea why?

**Comment by brunocodutra** [comment]
It seems that the generic URL for the latest release of boost at sourceforge is linking to a `7-zip` compressed package instead of `bzip2`, which is very unfortunate becase `tar` doesn't seem to be able to handle it.

**Comment by ldionne** [comment]
Yeah, just saw this too

```sh
> wget --no-check-certificate  -O - https://sourceforge.net/projects/boost/files/latest/download > boost.tar.bz2
--2016-12-11 09:15:00--  https://sourceforge.net/projects/boost/files/latest/download
Resolving sourceforge.net... 216.34.181.60
Connecting to sourceforge.net|216.34.181.60|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: http://downloads.sourceforge.net/project/boost/boost/1.62.0/boost_1_62_0.7z?r=&ts=1481476500&use_mirror=superb-sea2 [following]
--2016-12-11 09:15:01--  http://downloads.sourceforge.net/project/boost/boost/1.62.0/boost_1_62_0.7z?r=&ts=1481476500&use_mirror=superb-sea2
Resolving downloads.sourceforge.net... 216.34.181.59
Connecting to downloads.sourceforge.net|216.34.181.59|:80... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://superb-sea2.dl.sourceforge.net/project/boost/boost/1.62.0/boost_1_62_0.7z [following]
--2016-12-11 09:15:01--  https://superb-sea2.dl.sourceforge.net/project/boost/boost/1.62.0/boost_1_62_0.7z
Resolving superb-sea2.dl.sourceforge.net... 209.160.57.180
Connecting to superb-sea2.dl.sourceforge.net|209.160.57.180|:443... ^C
```

**Comment by ldionne** [comment]
I'm not too sure how to ask for bz2 archives from sourceforge. I'm also not sure whether this change of behavior is a bug on their end (possibly?).

**Comment by brunocodutra** [comment]
> I'm not too sure how to ask for bz2 archives from sourceforge. 

AFAIK the only way to do that requires specifying the version we want to download, which would be a huge PITA to maintain, unless we get the latest tag from github and generate the URL on the fly.

> I'm also not sure whether this change of behavior is a bug on their end (possibly?).

It looks like a bug indeed, I just tried the URL on a browser and it starts downloading an archive with the misleading extension `bz2`.

**Comment by brunocodutra** [comment]
for reference, this is a way to get the latest tag from github using `curl`

```.sh
$ curl -Ls https://github.com/boostorg/boost/tags | awk '/tag-name/{print $3;exit}' FS='[<>]'
$ boost-1.63.0-beta1
```
but as you can see we would have to deal with pre-releases, which sucks.

**Pull request merged**
